image: gcc

stages:
  - vm
  - fixedpoint
  - binary
  - test

vm:
  stage: vm
  script:
    - make bin/vm
  artifacts:
    paths:
      - bin/vm

fasl fixed point:
  stage: fixedpoint
  script:
    - make fasl/ol.fasl
  artifacts:
    paths:
      - fasl/ol.fasl

ol:
  stage: binary
  script:
    - make bin/ol
  artifacts:
    paths:
      - bin/ol

test:
  stage: test
  script:
     - ./bin/ol --run tests/theorem-rand.scm -n 1000

cache:
  paths:
    - bin/*
    - fasl/*
    - c/*
