image: gcc

stages:
  - fasl
  - binary
  - documentation

fasl fixedpoint:
  stage: fasl
  script: make fasl/ol.fasl
  artifacts:
    paths:
      - bin/vm
      - fasl/ol.fasl

binary:
  stage: binary
  dependencies: fasl
  script: make bin/ol
  artifacts:
    paths:
      - bin/ol

documentation:
  stage: documentation
  dependencies: binary
  script: make documentation

