image: gcc

build:
  stage: fasl fixed point
  script:
    - make fasl/ol.fasl
  artifacts:
    paths:
      - bin/vm
      - fasl/ol.fasl

build:
  stage: ol
  script:
    - make bin/ol
  artifacts:
    paths:
      - bin/ol

test:
  stage: theorem-rand 1000 rounds
  script:
     - ./bin/ol --run tests/theorem-rand.scm -n 1000
