language: c

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

notifications:
  irc:
    channels: "chat.freenode.net#owl-lisp"
    template: "%{branch}/%{commit}: %{result} (%{author}: %{commit_subject})"
    skip_join: true
    use_notice: true

before_script: uname -a

script: make 'CFLAGS=-Wall -O2'
