language: c

before_install: 
  - echo "HELLO LOG?"
  - uname | grep Linux && sudo apt-get install -y gcc-multilib

os: 
  - linux
  - osx

compiler:
  - clang
  - gcc

env:
  - CFLAGS="-O2"
  - CFLAGS="-O2 -m32"
   
script: make
